// GENERATED from backend/app/data/sectors.py - keep in sync when adding sectors.
export const SECTOR_ORDER = ["saas", "fintech", "ev", "healthcare", "cyber", "cloud_infra", "consumer", "media", "semis", "real_estate", "industrials", "energy", "aerospace_defense", "telecom", "renewables", "financials", "logistics", "ecommerce", "medtech", "biotech", "materials", "travel", "staples", "insurance", "utilities", "autos", "gaming", "edtech", "agriculture"] as const;
export type SectorKey = (typeof SECTOR_ORDER)[number];
export const SECTOR_LABELS: Record<string, string> = {
  "saas": "SaaS",
  "fintech": "Fintech",
  "ev": "Electric Vehicles",
  "healthcare": "Healthcare",
  "cyber": "Cybersecurity",
  "cloud_infra": "Cloud Infra",
  "consumer": "Consumer",
  "media": "Media",
  "semis": "Semiconductors",
  "real_estate": "Real Estate",
  "industrials": "Industrials",
  "energy": "Energy",
  "aerospace_defense": "Aerospace & Defense",
  "telecom": "Telecom",
  "renewables": "Renewables",
  "financials": "Financials",
  "logistics": "Logistics & Transport",
  "ecommerce": "E-commerce & Retail",
  "medtech": "MedTech",
  "biotech": "Biotech",
  "materials": "Materials & Mining",
  "travel": "Travel & Leisure",
  "staples": "Consumer Staples",
  "insurance": "Insurance",
  "utilities": "Utilities",
  "autos": "Autos & Parts",
  "gaming": "Gaming",
  "edtech": "Education",
  "agriculture": "Agriculture"
};
export const SECTOR_BLURBS: Record<string, string> = {
  "saas": "Subscription software and platforms",
  "fintech": "Payments, lending and financial software",
  "ev": "EV makers, batteries and charging",
  "healthcare": "Providers, pharma and health services",
  "cyber": "Security software and services",
  "cloud_infra": "Data centers, hosting and dev infrastructure",
  "consumer": "Retail, restaurants and consumer brands",
  "media": "Streaming, publishing and advertising",
  "semis": "Chips, equipment and design",
  "real_estate": "REITs and property services",
  "industrials": "Machinery, automation and building products",
  "energy": "Oil, gas, midstream and services",
  "aerospace_defense": "Primes, suppliers and defense tech",
  "telecom": "Carriers, towers and satellite",
  "renewables": "Solar, storage, hydrogen and clean power",
  "financials": "Banks, brokers, exchanges and asset managers",
  "logistics": "Freight, rail, airlines and delivery",
  "ecommerce": "Online marketplaces and big-box retail",
  "medtech": "Devices, diagnostics and life-science tools",
  "biotech": "Drug developers and gene editing",
  "materials": "Chemicals, metals, mining and building materials",
  "travel": "Hotels, cruise, casinos and booking",
  "staples": "Food, beverage and household products",
  "insurance": "P&C, life and reinsurance",
  "utilities": "Regulated power, gas and water",
  "autos": "Automakers, suppliers and dealers",
  "gaming": "Video games, esports and betting",
  "edtech": "Online learning and for-profit education",
  "agriculture": "Crop inputs, grain and farm equipment"
};
export const sectorLabel = (k: string): string => SECTOR_LABELS[k] || k;
